services:
  alex-notebook:
    container_name: alexa-notebook 
    ports:
      - 8888:8888
      - 6006:6006
    build: . 
    volumes:
      - ./:/tf
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


